# Generated by Django 5.2.4 on 2025-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
