# Generated by Django 5.2.4 on 2025-08-03 08:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_descriptin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
