# Generated by Django 5.2.4 on 2025-08-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptin',
            new_name='description',
        ),
    ]
