# Generated by Django 5.2.4 on 2025-11-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Delivered ', 'Delivered '), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
